### PR TITLE
New Anchoring Logic for Advanced Use Cases

### PR DESCRIPTION
**Pull request by creativecreatorormaybenot**
## Description

Hi @rrousselGit, this PR accomplishes a slight refactor of the `flutter_portal` package to allow for some more advanced and improved use cases that were previously impossible to achieve.

Here is an example video of one of the use cases:

https://user-images.githubusercontent.com/19204050/154726869-894587bb-10e2-4a36-9e8d-315487f626ee.mp4

### Refactoring

There are basically two parts to the refactor:

1. The introduction of the abstract `Anchor` class.
2. Renaming / simplification of existing concepts.

The idea behind the `Anchor` class is to provide an abstract interface that is disconnected from the actual layout implementation to take care of anchoring a portal follower to its target.  
There are default implementations, but in order to make the parameters and outputs of the anchors understandable, we felt like it was necessary to align the naming everywhere.

### Non-fragility

The new logic should be super solid because it makes use of a custom link implementation that can handle the offsets in a way that essentially perfectly integrates with the existing `LayerLink` concepts and the framework. This means that there are no hacky workaround or additional layout / painting calls to make this work but the offsets are directly extracted from the link.

## Contributing

We realize that you @rrousselGit do not have time to maintain this package at this time. That is why I completed the full refactor already instead of pushing that work onto you.

If you can give generally share your thoughts on whether and how this can be integrated into the repo / package, that would be extremely helpful, hopefully for everyone 🙏

### CODE REVIEW

**Comment by venkatd** [comment]
Hi @rrousselGit!

I should mention that the refactor and extension should address the following issues:

#24 
#13 
#33 

It allow solves some issues in our own app like:
- Allows auto-complete boxes to match the width of their target
- Allows use cases where we can avoid things getting cut-off. For example, we have a tooltip implementation that renders above the target by default, but if it will get cut-off, it renders below.
- Is open to extension so users of flutter_portal can implement their own custom layout logic just by implementing the `Anchor` class.

There are others it resolves too, but these are the ones that stand out to me :)

**Comment by fzyzcjy** [comment]
Btw, maybe need a merge from upstream (rrousselGit:master), since I have made a bugfix here: https://github.com/rrousselGit/flutter_portal/commit/69d56aee1fc9fe790c9c5a2e940f494432551dfb

**Comment by fzyzcjy** [comment]
IMHO this is a great PR and looks promising! I do have the permission to merge, but definitely, I should respect @rrousselGit.

**Comment by creativecreatorormaybenot** [comment]
@fzyzcjy Thanks! I merged upstream into my branch :)

**Comment by rrousselGit** [comment]
Feel free to merge and review on your own @fzyzcjy  :)

The only thing you need me for I believe is publishing, until we sort out rights for it.

**Comment by fzyzcjy** [comment]
@rrousselGit Ok :)

> The only thing you need me for I believe is publishing, until we sort out rights for it.

Btw @tkfinitefield has contacted me indeed in January using email, but I seldom check that mailbox so I missed it :( Only a few days ago did I see and reply to his email, as well as `pub.dev`'s invitation link (which is already expired).

**Comment by fzyzcjy** [comment]
Hi, this does not seem to work on flutter 2.10?

Please have a look at: https://github.com/rrousselGit/flutter_portal/issues/13#issuecomment-1054720736

**Comment by creativecreatorormaybenot** [comment]
@fzyzcjy Hi, that is right - there was a commit on stable that made the leader private. However,.this has been fixed.again later. On `master`, it works. Maybe we want to rollback until the next stable version 🤔

**Comment by fzyzcjy** [comment]
Interesting... Could you please provide a bit more details about this commit and fixes (sounds like there should exist some PR with discussions about this?)

A naive thought: Can we copy-and-paste the LayerLink into this repository and modify that field?

> Maybe we want to rollback until the next stable version 

That may be the final workaround :( But then we need to wait for about 3 months...

**Comment by creativecreatorormaybenot** [comment]
@fzyzcjy you can follow the links in https://github.com/flutter/flutter/pull/96486

**Comment by creativecreatorormaybenot** [comment]
@fzyzcjy we can request a **cherry pick** for that PR. Then this could go to stable in the next days / weeks 🚀

**Comment by fzyzcjy** [comment]
@creativecreatorormaybenot Sounds great!

**Comment by fzyzcjy** [comment]
@creativecreatorormaybenot Hi, that PR in Flutter repo is P6, which means "unlikely to proceed". Thus maybe we should do something else.

I tried to copy Flutter's original LayerLink together with its friends who need using its private methods. PR is at: https://github.com/rrousselGit/flutter_portal/pull/47#

However, it is failing. Could you please have a look at it? Because the failed tests seem to be originated from this PR.

**Comment by fzyzcjy** [comment]
Btw I am wondering why `PortalEntry` is renamed to `PortalTarget`? This sounds like a breaking change :(

**Comment by creativecreatorormaybenot** [comment]
@fzyzcjy yes - this was part of **Refactoring 2.**.

The concepts throughout the package were somewhat off, so we felt the need to simplify / unify them.

**Comment by fzyzcjy** [comment]
@creativecreatorormaybenot Agree! Looking forward to your further refactoring!

**Comment by venkatd** [comment]
@fzyzcjy do you mean it may take some time before LayerLink is made public again on the Flutter stable channel?

Yes as @creativecreatorormaybenot said, it was easy to mix up the meaning of some of names before. So the words "follower" and "target" were meant to clarify that the follower widget follows the target.

**Comment by fzyzcjy** [comment]
@venkatd 

> @fzyzcjy do you mean it may take some time before LayerLink is made public again on the Flutter stable channel?

I guess 3 months

**Pull request merged**
